# Generated by Django 4.2.2 on 2023-06-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhostpassportimage',
            old_name='user',
            new_name='user_id',
        ),
    ]
