# Generated by Django 4.2.2 on 2023-07-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhost',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
