# Generated by Django 4.2.2 on 2023-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
