# Generated by Django 4.2.2 on 2023-07-03 08:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='rich_field',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
