# Generated by Django 4.2.2 on 2023-07-03 08:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours_info', '0002_page_rich_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='rich_field',
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
