# Generated by Django 4.2.2 on 2023-07-03 08:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours_info', '0003_remove_page_rich_field_alter_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
