# Generated by Django 4.2.2 on 2023-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
