# Generated by Django 4.2.2 on 2023-07-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tours.city'),
        ),
    ]
