# Generated by Django 4.2.2 on 2023-07-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours', '0002_alter_tour_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='travel_tours.city'),
        ),
    ]
