# Generated by Django 4.2.2 on 2023-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tours', '0002_tourtype_alter_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='total_rating',
            field=models.BigIntegerField(default=1),
        ),
    ]
