# Generated by Django 4.2.2 on 2023-06-22 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_tours', '0002_remove_favorite_tours_alter_favorite_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
