# Generated by Django 4.2.2 on 2023-06-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('travel_tours', '0004_tour_is_active_alter_favorite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='account.userhost'),
        ),
    ]
